name: 'Github Migrations Backup'
author: 'oscar-b'
description: 'Backup a Github Org with one Action'
inputs:
    githubOrganization:
        description: 'The GitHub org you want to make a backup for'
        required: true
    githubRepository:
        description: A single repository to backup, instead of all repositories in the organisation
    apiKey:
        description: 'The API token necessary to talk to the GitHub API'
        required: true
    repositoriesPerJob:
        description: Number of repositories to backup in each job
        required: true
        default: '50'
outputs:
    backupFiles:
        description: The files with all the backups
    backupDirectory:
        description: The directory with all the backups
runs:
    using: 'node20'
    main: 'dist/index.js'
branding:
    icon: 'upload-cloud'
    color: 'orange'
