name: 'Github Migrations Backup'
author: 'oscar-b'
description: 'Backup a Github Org with one Action'
inputs:
    GH_ORG:
        description: 'The GitHub org you want to make a backup for'
        required: true
    GH_REPO:
        description: A single repository to backup, instead of all repositories in the organisation
    GH_APIKEY:
        description: 'The API token necessary to talk to the GitHub API'
        required: true
outputs:
    backupFile:
        description: The file with all the backups
runs:
    using: 'node16'
    main: 'dist/index.js'
branding:
    icon: 'upload-cloud'
    color: 'orange'
